// Generated by CoffeeScript 1.6.3
var assembleReturningPromise, core, hinoki, ioc;

core = require('./core');

ioc = require('./ioc');

module.exports = hinoki = core;

assembleReturningPromise = function() {
  return hinoki.assembleReturningPromise.call(null, arguments);
};

hinoki.requireReturningPromise = ioc.requireReturningPromise(hinoki.find, assembleReturningPromise);

hinoki.assembleReturningPromise = ioc.assembleReturningPromise(core.parseFunctionArguments, hinoki.requireReturningPromise, core.callFactoryReturningPromise);

hinoki.inject = ioc.inject(hinoki.requireReturningPromise, hinoki.reasonToError);
