// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

module.exports = {
  find: function(array, predicate) {
    var i, length;
    i = 0;
    length = array.length;
    while (i < length) {
      if (predicate(array[i])) {
        return array[i];
      }
      i++;
    }
    return null;
  },
  arrayOfStringsHasDuplicates: function(array) {
    var i, length, value, valuesSoFar;
    i = 0;
    length = array.length;
    valuesSoFar = {};
    while (i < length) {
      value = array[i];
      if (Object.prototype.hasOwnProperty.call(valuesSoFar, value)) {
        return true;
      }
      valuesSoFar[value] = true;
      i++;
    }
    return false;
  },
  arrayify: function(arg) {
    if (Array.isArray(arg)) {
      return arg;
    }
    if (arg == null) {
      return [];
    }
    return [arg];
  },
  startingWith: function(xs, x) {
    var index;
    index = xs.indexOf(x);
    if (index === -1) {
      return [];
    }
    return xs.slice(index);
  },
  parseFunctionArguments: function(fun) {
    var argumentPart, dependencies, string;
    if ('function' !== typeof fun) {
      throw new Error('argument must be a function');
    }
    string = fun.toString();
    argumentPart = string.slice(string.indexOf('(') + 1, string.indexOf(')'));
    dependencies = argumentPart.match(/([^\s,]+)/g);
    if (dependencies != null) {
      return dependencies;
    } else {
      return [];
    }
  },
  selectKeys: function() {
    var keys, object, result;
    object = arguments[0], keys = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    result = {};
    keys.forEach(function(key) {
      return result[key] = object[key];
    });
    return result;
  },
  merge: function() {
    var objects, result;
    objects = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    result = {};
    objects.forEach(function(object) {
      return Object.keys(object).forEach(function(key) {
        return result[key] = object[key];
      });
    });
    return result;
  }
};
